export const REQUEST_JOB_DATA = 'REQUEST_JOB_DATA'
export const RECEIVE_JOB_DATA = 'RECEIVE_JOB_DATA'
export const ERROR_JOB_DATA = 'ERROR_JOB_DATA'
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE'
export const REQUEST_JOB_COUNT_DATA = 'REQUEST_JOB_COUNT_DATA'
export const RECEIVE_JOB_COUNT = 'RECEIVE_JOB_COUNT'
export const ERROR_JOB_COUNT_DATA = 'ERROR_JOB_COUNT_DATA'
export const CHANGE_TCIN_FILTER = 'CHANGE_TCIN_FILTER'
export const CHANGE_CURRENT_TAB = 'CHANGE_CURRENT_TAB'

export const REQUEST_TOTAL_TCINS = 'REQUEST_TOTAL_TCINS'
export const RECEIVE_TOTAL_TCINS = 'RECEIVE_TOTAL_TCINS'

export const REQUEST_TOTAL_PRIMARY_IMAGES = 'REQUEST_TOTAL_PRIMARY_IMAGES'
export const RECEIVE_TOTAL_PRIMARY_IMAGES = 'RECEIVE_TOTAL_PRIMARY_IMAGES'

export const REQUEST_TOTAL_ALTERNATE_IMAGES = 'REQUEST_TOTAL_ALTERNATE_IMAGES'
export const RECEIVE_TOTAL_ALTERNATE_IMAGES = 'RECEIVE_TOTAL_ALTERNATE_IMAGES'

export const REQUEST_TOTAL_SWATCH_IMAGES = 'REQUEST_TOTAL_SWATCH_IMAGES'
export const RECEIVE_TOTAL_SWATCH_IMAGES = 'RECEIVE_TOTAL_SWATCH_IMAGES'

export const REQUEST_TOTAL_VALIDATED_IMAGES = 'REQUEST_TOTAL_VALIDATED_IMAGES'
export const RECEIVE_TOTAL_VALIDATED_IMAGES = 'RECEIVE_TOTAL_VALIDATED_IMAGES'

export const REQUEST_FILE_STATUS = 'REQUEST_FILE_STATUS'
export const RECEIVE_FILE_STATUS = 'RECEIVE_FILE_STATUS'

export const REQUEST_UPDATE_LOG_LEVEL = 'REQUEST_UPDATE_LOG_LEVEL'
export const SUCCESS_UPDATE_LOG_LEVEL = 'SUCCESS_UPDATE_LOG_LEVEL'

export const SET_LOG_SERVER_URL = 'SET_LOG_SERVER_URL'
export const SET_LOG_LEVEL = 'SET_LOG_LEVEL'

export const REQUEST_TOTAL_TCIN_BASED_IMAGES = 'REQUEST_TOTAL_TCIN_BASED_IMAGES'
export const RECEIVE_TOTAL_TCIN_BASED_IMAGES = 'RECEIVE_TOTAL_TCIN_BASED_IMAGES'

export const TOGGLE_FILE_INFO = 'TOGGLE_FILE_INFO'

export const REQUEST_RETRY_EVENT = 'REQUEST_RETRY_EVENT'
export const SUCCESS_RETRY_EVENT = 'SUCCESS_RETRY_EVENT'

export const CHANGE_TO_DATE = 'CHANGE_TO_DATE'
export const CHANGE_FROM_DATE = 'CHANGE_FROM_DATE'

export const TOGGLE_MIGRATION = 'TOGGLE_MIGRATION'

export const CHANGE_SYNC_TCINS = 'CHANGE_SYNC_TCINS'

export const REQUEST_TCINS_DATA = 'REQUEST_TCINS_DATA'
export const SUCCESS_TCINS_DATA = 'SUCCESS_TCINS_DATA'

export const REQUEST_SYNC_TCINS_DATA = 'REQUEST_SYNC_TCINS_DATA'
export const SUCCESS_SYNC_TCINS_DATA = 'SUCCESS_SYNC_TCINS_DATA'

export const ITEM_DEBUGGER_SELECTED_ITEMS = 'ITEM_DEBUGGER_SELECTED_ITEMS'
export const ITEM_DEBUGGER_REQUEST_ITEM_DATA = 'ITEM_DEBUGGER_REQUEST_ITEM_DATA'
export const ITEM_DEBUGGER_SUCCESS_ITEM_DATA = 'ITEM_DEBUGGER_SUCCESS_ITEM_DATA'
export const ITEM_DEBUGGER_DISPLAY_ERROR = 'ITEM_DEBUGGER_DISPLAY_ERROR'
export const ITEM_DEBUGGER_CLEAR_ITEM_DETAILS = 'ITEM_DEBUGGER_CLEAR_ITEM_DETAILS'
export const ITEM_DEBUGGER_TOGGLE_INCLUDE_VERSION = 'ITEM_DEBUGGER_TOGGLE_INCLUDE_VERSION'
